import fs from 'node:fs'
import path from 'node:path'
import { PNG } from 'pngjs'
import { classifyTrackMasks, type TrackPixelSource } from '../server/ServerTrackMap'

const ROOT = process.cwd()
const TRACK_PATH = path.resolve(ROOT, 'public/assets/tracks/Mario Circuit 1.png')
const COLLISION_PATH = path.resolve(
  ROOT,
  'public/assets/tracks/Mario Circuit 1 - Collision.png',
)
const OUTPUT_PATH = path.resolve(ROOT, 'cloudflare/src/generatedTrackData.ts')

function readPng(filePath: string): Promise<TrackPixelSource> {
  return new Promise((resolve, reject) => {
    fs.createReadStream(filePath)
      .pipe(new PNG())
      .on('parsed', function parsed(this: PNG) {
        resolve({ width: this.width, height: this.height, data: this.data })
      })
      .on('error', reject)
  })
}

const [surface, collision] = await Promise.all([
  readPng(TRACK_PATH),
  readPng(COLLISION_PATH),
])
const masks = classifyTrackMasks(surface, collision)

const source = `// Generated by scripts/generate-cloudflare-track-data.ts. Do not edit.\n` +
  `export const TRACK_WIDTH = ${masks.width}\n` +
  `export const TRACK_HEIGHT = ${masks.height}\n` +
  `export const TRACK_ROAD_MASK_BASE64 = '${Buffer.from(masks.roadMask).toString('base64')}'\n` +
  `export const TRACK_SOLID_MASK_BASE64 = '${Buffer.from(masks.solidMask).toString('base64')}'\n`

fs.writeFileSync(OUTPUT_PATH, source)
console.log(
  `[retro_kart] generated Cloudflare track masks (${masks.width}x${masks.height}, ${Math.round(source.length / 1024)} KiB)`,
)
